### ISSUE TITLE
The mptcp-proxy client automatically exits the process, indicating a bug that needs optimization.

### ISSUE THREAD

**Issue by maojianyou** [myml/mptcp-proxy#3]
2024/05/06 23:09:11 readfrom tcp 172.31.82.2:6000->172.31.82.32:33680: closed connection
2024/05/06 23:09:11 writeto tcp 172.31.82.2:6000->172.31.82.32:33680: closed connection
panic: send on closed channel

goroutine 33 [running]:
main.biCopy.func2()
        /opt/mptcp-proxy/main.go:126 +0x116
created by main.biCopy in goroutine 31
        /opt/mptcp-proxy/main.go:121 +0x125
^C
[1]+  Exit 2                  nohup ./mptcp-proxy -c :6000 -p "172.16.71.1:12345,172.16.72.1:12345"
root@ubuntu2404:/opt/mptcp-proxy# tail -f nohup.out 
DEBUG multipath: subflow.go:387 Took 33.557313ms to close subflow
2024/05/06 23:09:11 readfrom tcp 172.31.82.2:6000->172.31.82.32:33680: closed connection
2024/05/06 23:09:11 writeto tcp 172.31.82.2:6000->172.31.82.32:33680: closed connection
panic: send on closed channel

goroutine 33 [running]:
main.biCopy.func2()
        /opt/mptcp-proxy/main.go:126 +0x116
created by main.biCopy in goroutine 31
        /opt/mptcp-proxy/main.go:121 +0x125

**Comment by myml** [comment]
Thanks for your feedback, it has been fixed
